export interface CountryInfo {
  code: string;
  name: string;
  flag: string;
  currency: string;
  currencySymbol: string;
  rateToUsd: number;
  popular?: boolean;
  paymentMethods?: string[];
  banks?: string[];
}

export const COUNTRIES: CountryInfo[] = [
  // ── Popular / High Volume Countries ──
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    currency: "NGN",
    currencySymbol: "₦",
    rateToUsd: 1600,
    popular: true,
    paymentMethods: ["Instant Bank Transfer (NIBSS / Swiftsats)", "OPay / Moniepoint Transfer", "Debit Card"],
    banks: [
      "Access Bank",
      "Zenith Bank",
      "Guaranty Trust Bank (GTBank)",
      "First Bank of Nigeria",
      "United Bank for Africa (UBA)",
      "Kuda Microfinance Bank",
      "OPay Digital Services",
      "Moniepoint Microfinance Bank",
      "PalmPay",
      "Stanbic IBTC Bank",
      "Fidelity Bank",
      "Sterling Bank",
      "Wema Bank / ALAT",
      "Union Bank of Nigeria",
      "FCMB (First City Monument Bank)"
    ]
  },
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    currency: "USD",
    currencySymbol: "$",
    rateToUsd: 1,
    popular: true,
    paymentMethods: ["Debit / Credit Card (Visa & Mastercard)", "Instant ACH Bank Transfer", "Apple Pay / Google Pay", "Wire Transfer"],
    banks: ["JPMorgan Chase", "Bank of America", "Wells Fargo", "Citibank", "Capital One", "U.S. Bank", "PNC Bank", "Truist", "TD Bank", "Charles Schwab"]
  },
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
    rateToUsd: 0.77,
    popular: true,
    paymentMethods: ["Faster Payments Service (FPS)", "Revolut / Monzo Instant", "Apple Pay", "Debit Card"],
    banks: ["Barclays", "HSBC UK", "Lloyds Bank", "NatWest", "Revolut", "Monzo", "Starling Bank", "Santander UK", "TSB Bank"]
  },
  {
    code: "EU",
    name: "European Union (Eurozone)",
    flag: "🇪🇺",
    currency: "EUR",
    currencySymbol: "€",
    rateToUsd: 0.92,
    popular: true,
    paymentMethods: ["SEPA Instant Credit Transfer", "iDEAL / Sofort", "Apple Pay", "Debit / Credit Card"],
    banks: ["Deutsche Bank", "BNP Paribas", "ING Group", "Santander", "BBVA", "Crédit Agricole", "Société Générale", "N26", "Revolut EU"]
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    currency: "CAD",
    currencySymbol: "C$",
    rateToUsd: 1.38,
    popular: true,
    paymentMethods: ["Interac e-Transfer", "Debit / Credit Card", "Wire Transfer"],
    banks: ["Royal Bank of Canada (RBC)", "TD Canada Trust", "Scotiabank", "BMO (Bank of Montreal)", "CIBC", "National Bank of Canada"]
  },
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    currency: "AUD",
    currencySymbol: "A$",
    rateToUsd: 1.52,
    popular: true,
    paymentMethods: ["PayID / Osko Instant", "Debit / Credit Card", "Direct Bank Transfer"],
    banks: ["Commonwealth Bank (CBA)", "Westpac", "ANZ Bank", "National Australia Bank (NAB)", "Macquarie Bank"]
  },
  {
    code: "GH",
    name: "Ghana",
    flag: "🇬🇭",
    currency: "GHS",
    currencySymbol: "GH₵",
    rateToUsd: 15.6,
    popular: true,
    paymentMethods: ["MTN Mobile Money (MoMo)", "Telecel Cash", "Bank Transfer (GhIPSS)"],
    banks: ["GCB Bank", "Ecobank Ghana", "Stanbic Bank Ghana", "Absa Bank Ghana", "Fidelity Bank Ghana", "CalBank"]
  },
  {
    code: "KE",
    name: "Kenya",
    flag: "🇰🇪",
    currency: "KES",
    currencySymbol: "KSh",
    rateToUsd: 129.5,
    popular: true,
    paymentMethods: ["M-Pesa Express", "Airtel Money", "PesaLink Bank Transfer"],
    banks: ["KCB Bank", "Equity Bank", "Co-operative Bank of Kenya", "Standard Chartered Kenya", "Absa Bank Kenya", "NCBA Bank"]
  },
  {
    code: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    currency: "ZAR",
    currencySymbol: "R",
    rateToUsd: 17.8,
    popular: true,
    paymentMethods: ["Instant EFT (PayFast / Ozow)", "Capitec Pay", "Debit Card"],
    banks: ["Standard Bank", "First National Bank (FNB)", "Absa Group", "Nedbank", "Capitec Bank", "Investec"]
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    currency: "AED",
    currencySymbol: "AED",
    rateToUsd: 3.67,
    popular: true,
    paymentMethods: ["Instant UAE Bank Transfer", "Debit / Credit Card", "Apple Pay"],
    banks: ["First Abu Dhabi Bank (FAB)", "Emirates NBD", "Abu Dhabi Commercial Bank (ADCB)", "Dubai Islamic Bank", "Mashreq Bank"]
  },
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    currency: "INR",
    currencySymbol: "₹",
    rateToUsd: 83.9,
    popular: true,
    paymentMethods: ["UPI Instant (Google Pay, PhonePe, Paytm)", "IMPS Bank Transfer", "Debit Card"],
    banks: ["State Bank of India (SBI)", "HDFC Bank", "ICICI Bank", "Axis Bank", "Kotak Mahindra Bank", "Punjab National Bank"]
  },
  {
    code: "BR",
    name: "Brazil",
    flag: "🇧🇷",
    currency: "BRL",
    currencySymbol: "R$",
    rateToUsd: 5.45,
    popular: true,
    paymentMethods: ["PIX Instant Transfer", "TED / DOC", "Cartão de Crédito"],
    banks: ["Itaú Unibanco", "Banco do Brasil", "Bradesco", "Nubank", "Santander Brasil", "Caixa Econômica"]
  },
  {
    code: "PH",
    name: "Philippines",
    flag: "🇵🇭",
    currency: "PHP",
    currencySymbol: "₱",
    rateToUsd: 56.5,
    popular: true,
    paymentMethods: ["GCash", "Maya (PayMaya)", "InstaPay Bank Transfer"],
    banks: ["BDO Unibank", "BPI (Bank of the Philippine Islands)", "Metrobank", "UnionBank of the Philippines", "Land Bank"]
  },

  // ── Global Countries Alphabetical ──
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", currency: "AFN", currencySymbol: "Af", rateToUsd: 68 },
  { code: "AL", name: "Albania", flag: "🇦🇱", currency: "ALL", currencySymbol: "L", rateToUsd: 91 },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", currency: "DZD", currencySymbol: "DA", rateToUsd: 133 },
  { code: "AD", name: "Andorra", flag: "🇦🇩", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "AO", name: "Angola", flag: "🇦🇴", currency: "AOA", currencySymbol: "Kz", rateToUsd: 915 },
  { code: "AG", name: "Antigua & Barbuda", flag: "🇦🇬", currency: "XCD", currencySymbol: "$", rateToUsd: 2.7 },
  { code: "AR", name: "Argentina", flag: "🇦🇷", currency: "ARS", currencySymbol: "$", rateToUsd: 980 },
  { code: "AM", name: "Armenia", flag: "🇦🇲", currency: "AMD", currencySymbol: "֏", rateToUsd: 387 },
  { code: "AT", name: "Austria", flag: "🇦🇹", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", currency: "AZN", currencySymbol: "₼", rateToUsd: 1.7 },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", currency: "BSD", currencySymbol: "$", rateToUsd: 1 },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", currency: "BHD", currencySymbol: "BD", rateToUsd: 0.38 },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", currency: "BDT", currencySymbol: "৳", rateToUsd: 120 },
  { code: "BB", name: "Barbados", flag: "🇧🇧", currency: "BBD", currencySymbol: "$", rateToUsd: 2 },
  { code: "BY", name: "Belarus", flag: "🇧🇾", currency: "BYN", currencySymbol: "Br", rateToUsd: 3.28 },
  { code: "BE", name: "Belgium", flag: "🇧🇪", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "BZ", name: "Belize", flag: "🇧🇿", currency: "BZD", currencySymbol: "BZ$", rateToUsd: 2 },
  { code: "BJ", name: "Benin", flag: "🇧🇯", currency: "XOF", currencySymbol: "CFA", rateToUsd: 605 },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", currency: "BTN", currencySymbol: "Nu.", rateToUsd: 83.9 },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", currency: "BOB", currencySymbol: "Bs.", rateToUsd: 6.91 },
  { code: "BA", name: "Bosnia & Herzegovina", flag: "🇧🇦", currency: "BAM", currencySymbol: "KM", rateToUsd: 1.8 },
  { code: "BW", name: "Botswana", flag: "🇧🇼", currency: "BWP", currencySymbol: "P", rateToUsd: 13.5 },
  { code: "BN", name: "Brunei", flag: "🇧🇳", currency: "BND", currencySymbol: "B$", rateToUsd: 1.32 },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", currency: "BGN", currencySymbol: "лв", rateToUsd: 1.8 },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", currency: "XOF", currencySymbol: "CFA", rateToUsd: 605 },
  { code: "BI", name: "Burundi", flag: "🇧🇮", currency: "BIF", currencySymbol: "FBu", rateToUsd: 2900 },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", currency: "KHR", currencySymbol: "៛", rateToUsd: 4070 },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", currency: "XAF", currencySymbol: "FCFA", rateToUsd: 605 },
  { code: "CV", name: "Cape Verde", flag: "🇨🇻", currency: "CVE", currencySymbol: "$", rateToUsd: 101 },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫", currency: "XAF", currencySymbol: "FCFA", rateToUsd: 605 },
  { code: "TD", name: "Chad", flag: "🇹🇩", currency: "XAF", currencySymbol: "FCFA", rateToUsd: 605 },
  { code: "CL", name: "Chile", flag: "🇨🇱", currency: "CLP", currencySymbol: "$", rateToUsd: 935 },
  { code: "CN", name: "China", flag: "🇨🇳", currency: "CNY", currencySymbol: "¥", rateToUsd: 7.12 },
  { code: "CO", name: "Colombia", flag: "🇨🇴", currency: "COP", currencySymbol: "$", rateToUsd: 4200 },
  { code: "KM", name: "Comoros", flag: "🇰🇲", currency: "KMF", currencySymbol: "CF", rateToUsd: 452 },
  { code: "CD", name: "Congo (DRC)", flag: "🇨🇩", currency: "CDF", currencySymbol: "FC", rateToUsd: 2850 },
  { code: "CG", name: "Congo (Republic)", flag: "🇨🇬", currency: "XAF", currencySymbol: "FCFA", rateToUsd: 605 },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", currency: "CRC", currencySymbol: "₡", rateToUsd: 520 },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", currency: "XOF", currencySymbol: "CFA", rateToUsd: 605 },
  { code: "HR", name: "Croatia", flag: "🇭🇷", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "CU", name: "Cuba", flag: "🇨🇺", currency: "CUP", currencySymbol: "$", rateToUsd: 24 },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", currency: "CZK", currencySymbol: "Kč", rateToUsd: 23.3 },
  { code: "DK", name: "Denmark", flag: "🇩🇰", currency: "DKK", currencySymbol: "kr", rateToUsd: 6.87 },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", currency: "DJF", currencySymbol: "Fdj", rateToUsd: 178 },
  { code: "DM", name: "Dominica", flag: "🇩🇲", currency: "XCD", currencySymbol: "$", rateToUsd: 2.7 },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", currency: "DOP", currencySymbol: "RD$", rateToUsd: 60.1 },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", currency: "USD", currencySymbol: "$", rateToUsd: 1 },
  { code: "EG", name: "Egypt", flag: "🇪🇬", currency: "EGP", currencySymbol: "E£", rateToUsd: 48.5 },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", currency: "USD", currencySymbol: "$", rateToUsd: 1 },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", currency: "XAF", currencySymbol: "FCFA", rateToUsd: 605 },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", currency: "ERN", currencySymbol: "Nfk", rateToUsd: 15 },
  { code: "EE", name: "Estonia", flag: "🇪🇪", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", currency: "SZL", currencySymbol: "E", rateToUsd: 17.8 },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", currency: "ETB", currencySymbol: "Br", rateToUsd: 118 },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", currency: "FJD", currencySymbol: "FJ$", rateToUsd: 2.24 },
  { code: "FI", name: "Finland", flag: "🇫🇮", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "FR", name: "France", flag: "🇫🇷", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "GA", name: "Gabon", flag: "🇬🇦", currency: "XAF", currencySymbol: "FCFA", rateToUsd: 605 },
  { code: "GM", name: "Gambia", flag: "🇬🇲", currency: "GMD", currencySymbol: "D", rateToUsd: 70 },
  { code: "GE", name: "Georgia", flag: "🇬🇪", currency: "GEL", currencySymbol: "₾", rateToUsd: 2.73 },
  { code: "DE", name: "Germany", flag: "🇩🇪", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "GR", name: "Greece", flag: "🇬🇷", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "GD", name: "Grenada", flag: "🇬🇩", currency: "XCD", currencySymbol: "$", rateToUsd: 2.7 },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", currency: "GTQ", currencySymbol: "Q", rateToUsd: 7.73 },
  { code: "GN", name: "Guinea", flag: "🇬🇳", currency: "GNF", currencySymbol: "FG", rateToUsd: 8600 },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", currency: "XOF", currencySymbol: "CFA", rateToUsd: 605 },
  { code: "GY", name: "Guyana", flag: "🇬🇾", currency: "GYD", currencySymbol: "G$", rateToUsd: 209 },
  { code: "HT", name: "Haiti", flag: "🇭🇹", currency: "HTG", currencySymbol: "G", rateToUsd: 132 },
  { code: "HN", name: "Honduras", flag: "🇭🇳", currency: "HNL", currencySymbol: "L", rateToUsd: 24.8 },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", currency: "HKD", currencySymbol: "HK$", rateToUsd: 7.77 },
  { code: "HU", name: "Hungary", flag: "🇭🇺", currency: "HUF", currencySymbol: "Ft", rateToUsd: 367 },
  { code: "IS", name: "Iceland", flag: "🇮🇸", currency: "ISK", currencySymbol: "kr", rateToUsd: 137 },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", currency: "IDR", currencySymbol: "Rp", rateToUsd: 15400 },
  { code: "IR", name: "Iran", flag: "🇮🇷", currency: "IRR", currencySymbol: "﷼", rateToUsd: 42000 },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", currency: "IQD", currencySymbol: "ع.د", rateToUsd: 1310 },
  { code: "IE", name: "Ireland", flag: "🇮🇪", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "IL", name: "Israel", flag: "🇮🇱", currency: "ILS", currencySymbol: "₪", rateToUsd: 3.75 },
  { code: "IT", name: "Italy", flag: "🇮🇹", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", currency: "JMD", currencySymbol: "J$", rateToUsd: 157 },
  { code: "JP", name: "Japan", flag: "🇯🇵", currency: "JPY", currencySymbol: "¥", rateToUsd: 152 },
  { code: "JO", name: "Jordan", flag: "🇯🇴", currency: "JOD", currencySymbol: "JD", rateToUsd: 0.71 },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", currency: "KZT", currencySymbol: "₸", rateToUsd: 485 },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", currency: "KWD", currencySymbol: "KD", rateToUsd: 0.31 },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", currency: "KGS", currencySymbol: "с", rateToUsd: 85.5 },
  { code: "LA", name: "Laos", flag: "🇱🇦", currency: "LAK", currencySymbol: "₭", rateToUsd: 21900 },
  { code: "LV", name: "Latvia", flag: "🇱🇻", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", currency: "LBP", currencySymbol: "L£", rateToUsd: 89500 },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", currency: "LSL", currencySymbol: "L", rateToUsd: 17.8 },
  { code: "LR", name: "Liberia", flag: "🇱🇷", currency: "LRD", currencySymbol: "$", rateToUsd: 195 },
  { code: "LY", name: "Libya", flag: "🇱🇾", currency: "LYD", currencySymbol: "LD", rateToUsd: 4.8 },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", currency: "MGA", currencySymbol: "Ar", rateToUsd: 4550 },
  { code: "MW", name: "Malawi", flag: "🇲🇼", currency: "MWK", currencySymbol: "MK", rateToUsd: 1740 },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", currency: "MYR", currencySymbol: "RM", rateToUsd: 4.35 },
  { code: "MV", name: "Maldives", flag: "🇲🇻", currency: "MVR", currencySymbol: "Rf", rateToUsd: 15.4 },
  { code: "ML", name: "Mali", flag: "🇲🇱", currency: "XOF", currencySymbol: "CFA", rateToUsd: 605 },
  { code: "MT", name: "Malta", flag: "🇲🇹", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", currency: "MRU", currencySymbol: "UM", rateToUsd: 39.6 },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", currency: "MUR", currencySymbol: "₨", rateToUsd: 46.5 },
  { code: "MX", name: "Mexico", flag: "🇲🇽", currency: "MXN", currencySymbol: "Mex$", rateToUsd: 19.3 },
  { code: "MD", name: "Moldova", flag: "🇲🇩", currency: "MDL", currencySymbol: "L", rateToUsd: 17.7 },
  { code: "MC", name: "Monaco", flag: "🇲🇨", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", currency: "MNT", currencySymbol: "₮", rateToUsd: 3410 },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "MA", name: "Morocco", flag: "🇲🇦", currency: "MAD", currencySymbol: "DH", rateToUsd: 9.85 },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", currency: "MZN", currencySymbol: "MT", rateToUsd: 63.9 },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", currency: "MMK", currencySymbol: "K", rateToUsd: 2100 },
  { code: "NA", name: "Namibia", flag: "🇳🇦", currency: "NAD", currencySymbol: "N$", rateToUsd: 17.8 },
  { code: "NP", name: "Nepal", flag: "🇳🇵", currency: "NPR", currencySymbol: "₨", rateToUsd: 134 },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", currency: "NZD", currencySymbol: "NZ$", rateToUsd: 1.63 },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", currency: "NIO", currencySymbol: "C$", rateToUsd: 36.8 },
  { code: "NE", name: "Niger", flag: "🇳🇪", currency: "XOF", currencySymbol: "CFA", rateToUsd: 605 },
  { code: "NO", name: "Norway", flag: "🇳🇴", currency: "NOK", currencySymbol: "kr", rateToUsd: 10.7 },
  { code: "OM", name: "Oman", flag: "🇴🇲", currency: "OMR", currencySymbol: "RO", rateToUsd: 0.38 },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", currency: "PKR", currencySymbol: "₨", rateToUsd: 278 },
  { code: "PA", name: "Panama", flag: "🇵🇦", currency: "USD", currencySymbol: "$", rateToUsd: 1 },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", currency: "PGK", currencySymbol: "K", rateToUsd: 3.95 },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", currency: "PYG", currencySymbol: "₲", rateToUsd: 7650 },
  { code: "PE", name: "Peru", flag: "🇵🇪", currency: "PEN", currencySymbol: "S/.", rateToUsd: 3.76 },
  { code: "PL", name: "Poland", flag: "🇵🇱", currency: "PLN", currencySymbol: "zł", rateToUsd: 3.95 },
  { code: "PT", name: "Portugal", flag: "🇵🇹", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "QA", name: "Qatar", flag: "🇶🇦", currency: "QAR", currencySymbol: "QR", rateToUsd: 3.64 },
  { code: "RO", name: "Romania", flag: "🇷🇴", currency: "RON", currencySymbol: "lei", rateToUsd: 4.58 },
  { code: "RU", name: "Russia", flag: "🇷🇺", currency: "RUB", currencySymbol: "₽", rateToUsd: 96 },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", currency: "RWF", currencySymbol: "FRw", rateToUsd: 1350 },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", currency: "SAR", currencySymbol: "SR", rateToUsd: 3.75 },
  { code: "SN", name: "Senegal", flag: "🇸🇳", currency: "XOF", currencySymbol: "CFA", rateToUsd: 605 },
  { code: "RS", name: "Serbia", flag: "🇷🇸", currency: "RSD", currencySymbol: "дин.", rateToUsd: 108 },
  { code: "SG", name: "Singapore", flag: "🇸🇬", currency: "SGD", currencySymbol: "S$", rateToUsd: 1.32 },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "SO", name: "Somalia", flag: "🇸🇴", currency: "SOS", currencySymbol: "Sh", rateToUsd: 571 },
  { code: "KR", name: "South Korea", flag: "🇰🇷", currency: "KRW", currencySymbol: "₩", rateToUsd: 1380 },
  { code: "ES", name: "Spain", flag: "🇪🇸", currency: "EUR", currencySymbol: "€", rateToUsd: 0.92 },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", currency: "LKR", currencySymbol: "Rs", rateToUsd: 295 },
  { code: "SD", name: "Sudan", flag: "🇸🇩", currency: "SDG", currencySymbol: "SDG", rateToUsd: 600 },
  { code: "SE", name: "Sweden", flag: "🇸🇪", currency: "SEK", currencySymbol: "kr", rateToUsd: 10.4 },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", currency: "CHF", currencySymbol: "CHF", rateToUsd: 0.88 },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", currency: "TWD", currencySymbol: "NT$", rateToUsd: 32.2 },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", currency: "TZS", currencySymbol: "TSh", rateToUsd: 2700 },
  { code: "TH", name: "Thailand", flag: "🇹🇭", currency: "THB", currencySymbol: "฿", rateToUsd: 33.6 },
  { code: "TG", name: "Togo", flag: "🇹🇬", currency: "XOF", currencySymbol: "CFA", rateToUsd: 605 },
  { code: "TT", name: "Trinidad & Tobago", flag: "🇹🇹", currency: "TTD", currencySymbol: "TT$", rateToUsd: 6.78 },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", currency: "TND", currencySymbol: "DT", rateToUsd: 3.1 },
  { code: "TR", name: "Turkey", flag: "🇹🇷", currency: "TRY", currencySymbol: "₺", rateToUsd: 34.2 },
  { code: "UG", name: "Uganda", flag: "🇺🇬", currency: "UGX", currencySymbol: "USh", rateToUsd: 3700 },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", currency: "UAH", currencySymbol: "₴", rateToUsd: 41.3 },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", currency: "UYU", currencySymbol: "$U", rateToUsd: 41.5 },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", currency: "UZS", currencySymbol: "so'm", rateToUsd: 12800 },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", currency: "VES", currencySymbol: "Bs.", rateToUsd: 39.5 },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", currency: "VND", currencySymbol: "₫", rateToUsd: 24700 },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", currency: "ZMW", currencySymbol: "ZK", rateToUsd: 26.5 },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", currency: "USD", currencySymbol: "$", rateToUsd: 1 },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // Nigeria

export function getCountryByCode(code: string): CountryInfo {
  if (!code) return DEFAULT_COUNTRY;
  const found = COUNTRIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
  return found || DEFAULT_COUNTRY;
}

export function searchCountries(query: string): CountryInfo[] {
  if (!query || !query.trim()) return COUNTRIES;
  const q = query.toLowerCase().trim();
  return COUNTRIES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.code.toLowerCase().includes(q) ||
      c.currency.toLowerCase().includes(q)
  );
}
