# Generated by Django 5.2.17 on 2026-09-09 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('logo_url', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('total_supply', models.DecimalField(decimal_places=2, default=1000000000.0, max_digits=28)),
                ('current_price_usd', models.DecimalField(decimal_places=8, default=0.001, max_digits=28)),
                ('market_cap_usd', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=28)),
                ('liquidity_usd', models.DecimalField(decimal_places=2, default=250000.0, max_digits=28)),
                ('change_24h', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rugged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_pin', models.CharField(default='admin123', max_length=64)),
                ('trading_fee_pct', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_trading_paused', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(db_index=True, max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('seed_hash', models.CharField(blank=True, max_length=256)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=28)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timeframe', models.CharField(default='1H', max_length=10)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='wallet_engine.memetoken')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=4)),
                ('base_currency', models.CharField(max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('token_amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=28)),
                ('fee_usd', models.DecimalField(decimal_places=8, default=0.0, max_digits=28)),
                ('tx_hash', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='wallet_engine.memetoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='wallet_engine.walletuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwapTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=20)),
                ('to_currency', models.CharField(max_length=20)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('gas_fee_usd', models.DecimalField(decimal_places=8, default=0.0, max_digits=28)),
                ('tx_hash', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='wallet_engine.walletuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('tx_hash', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='wallet_engine.walletuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('network_fee', models.DecimalField(decimal_places=8, default=0.0, max_digits=28)),
                ('destination_address', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallet_engine.walletuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, max_length=20)),
                ('available_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=28)),
                ('locked_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=28)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='wallet_engine.walletuser')),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to='wallet_engine.walletuser')),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
