# Generated by Django 5.2.17 on 2026-09-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
