# Generated by Django 5.2.17 on 2026-09-14 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0003_loginattempt_walletuser_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDepositWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Deposit Wallet', max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('network', models.CharField(default='Solana (SPL)', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveSmallIntegerField(default=1)),
                ('total_received_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=28)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='platformdeposit',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformdeposit',
            name='wallet_address_used',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='platformdeposit',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='platformdeposit',
            name='deposit_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='wallet_engine.platformdepositwallet'),
        ),
    ]
