# Generated by Django 5.2.17 on 2026-09-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0004_platformdepositwallet_platformdeposit_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='audit_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='network',
            field=models.CharField(default='TRON (TRC-20)', max_length=64),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_type',
            field=models.CharField(choices=[('INSTANT_REFUND', 'Instant 24h Refund'), ('TRADING_REVIEW', 'Trading Activity Review')], default='TRADING_REVIEW', max_length=32),
        ),
    ]
