# Generated by Django 5.2.17 on 2026-09-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0005_withdrawalrequest_audit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetoken',
            name='contract_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
