# Generated by Django 5.2.17 on 2026-09-22 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0006_memetoken_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(db_index=True, max_length=80, unique=True)),
                ('passcode', models.CharField(max_length=128)),
                ('slug', models.CharField(db_index=True, max_length=64, unique=True)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='walletuser',
            name='registered_via_slug',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='junior_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='wallet_engine.junioradmin'),
        ),
    ]
