# Generated by Django 5.2.17 on 2026-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0007_junioradmin_walletuser_registered_via_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memetoken',
            name='change_24h',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
