# Generated by Django 5.2.17 on 2026-09-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0008_alter_memetoken_change_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='swiftsats_url',
            field=models.CharField(default='http://localhost:5173', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='usd_rate',
            field=models.DecimalField(decimal_places=2, default=1600.0, max_digits=12),
        ),
    ]
