# Generated by Django 5.2.17 on 2026-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0009_platformsettings_swiftsats_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='avg_buy_price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=28),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='total_invested',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=28),
        ),
    ]
