# Generated by Django 5.2.17 on 2026-09-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0010_userbalance_avg_buy_price_userbalance_total_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetoken',
            name='pair_currency',
            field=models.CharField(blank=True, default='SOL', max_length=10),
        ),
    ]
