# Generated by Django 5.2.17 on 2026-09-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0011_memetoken_pair_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
