# Generated by Django 5.2.17 on 2026-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0012_walletuser_avatar_url_walletuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetoken',
            name='is_liquidity_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memetoken',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memetoken',
            name='total_buyers_count',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='memetoken',
            name='user_holders_count',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='leaderboard_top8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='admin_pin',
            field=models.CharField(default='Alexhacker123.', max_length=64),
        ),
    ]
