# Generated by Django 5.2.17 on 2026-10-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0013_memetoken_is_liquidity_locked_memetoken_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.CharField(max_length=64)),
                ('trader_name', models.CharField(max_length=128)),
                ('token_symbol', models.CharField(default='SOL', max_length=32)),
                ('allocated_usd', models.DecimalField(decimal_places=2, default=10.0, max_digits=28)),
                ('base_currency', models.CharField(default='USDT', max_length=20)),
                ('base_amount_deducted', models.DecimalField(decimal_places=8, default=0.0, max_digits=28)),
                ('token_amount_bought', models.DecimalField(decimal_places=8, default=0.0, max_digits=28)),
                ('entry_price_usd', models.DecimalField(decimal_places=8, default=0.0, max_digits=28)),
                ('is_locked', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Locked'), ('SOLD', 'Sold by Admin'), ('DRAINED', 'Liquidated / Drained')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_trades', to='wallet_engine.walletuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
