# Generated by Django 5.2.17 on 2026-10-05 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0014_copytradingposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_audience', models.CharField(choices=[('USER', 'Specific User'), ('ALL_USERS', 'All Users'), ('ADMINS', 'Admins Only'), ('JUNIOR_ADMINS', 'Junior Admins Only'), ('ALL_STAFF', 'All Staff')], default='USER', max_length=32)),
                ('user_identifier', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('DEPOSIT', 'Deposit Confirmed'), ('WITHDRAWAL', 'Withdrawal Status'), ('TRADE', 'Trade Execution'), ('SUPPORT', 'Support Ticket Update'), ('ANNOUNCEMENT', 'Announcement'), ('SECURITY', 'Security Alert'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=32)),
                ('link_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='wallet_engine.walletuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_identifier', models.CharField(db_index=True, max_length=128)),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('is_admin_device', models.BooleanField(default=False)),
                ('is_junior_admin_device', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('junior_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_subscriptions', to='wallet_engine.junioradmin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='wallet_engine.walletuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('user_identifier', models.CharField(db_index=True, max_length=128)),
                ('user_handle', models.CharField(blank=True, max_length=120, null=True)),
                ('user_email', models.CharField(blank=True, max_length=120, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(default='General Support', max_length=64)),
                ('message', models.TextField()),
                ('screenshot_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_junior_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='wallet_engine.junioradmin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='wallet_engine.walletuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Super Admin'), ('JUNIOR_ADMIN', 'Junior Admin / Support Agent')], max_length=20)),
                ('sender_name', models.CharField(default='Support Desk', max_length=120)),
                ('message', models.TextField()),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wallet_engine.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
