# Generated by Django 5.2.17 on 2026-10-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_engine', '0015_appnotification_pushsubscription_supportticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetoken',
            name='is_sell_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='sell_blocked_tokens',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
